version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  fastapi-app:
    image: teniuscom/plango-ai:latest
    container_name: fastapi-container
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongo_data:

networks:
  app-network:
    external: true  # spring 서버가 이미 쓰고 있는 동일 네트워크
    name: plango_app-network